# Generated by Django 4.2.4 on 2024-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('typeo', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('weight', models.FloatField()),
                ('touchscreen', models.BooleanField()),
                ('ips', models.BooleanField()),
                ('screen_size', models.FloatField()),
                ('resolution', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
